name: Manual Data Ingestion

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual ingestion'
        required: false
        default: 'Manual trigger'

jobs:
  ingest-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ingestion script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        QDRANT_URL: ${{ secrets.QDRANT_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      run: |
        echo "Running ingestion: ${{ github.event.inputs.reason }}"
        python scripts/ingest.py