name: Monthly Data Ingestion

on:
  schedule:
    # Runs at 2 AM UTC on the 1st of every month
    - cron: '0 2 1 * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  ingest-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ingestion script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        QDRANT_URL: ${{ secrets.QDRANT_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      run: |
        python scripts/ingest.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add documents/
        git diff --staged --quiet || git commit -m "chore: automated monthly data ingestion [skip ci]"
        git push
      continue-on-error: true  # Don't fail if no changes to commit
      
    - name: Upload ingestion artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ingestion-logs-${{ github.run_number }}
        path: |
          documents/
          *.log
        retention-days: 30

    - name: Send notification on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Monthly Ingestion Failed',
            body: `The monthly ingestion workflow failed. Check the logs: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
          })